config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :seasons
  resources :barns
  resources :tournaments
  resources :fights
  resources :roosters
end

app/models/season.rb
class Season < ApplicationRecord
    belongs_to :tournament
    
    has_many :fights, :dependent => :delete_all
    has_many :roosters, :dependent => :delete_all
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  
  before_action :get_season, only: [:show, :edit, :update, :destroy]

  def index
    @seasons = Season.all
  end

  def show
    @rooster = Rooster.new
    @barns = Array.new
    _barns = Barn.where( tournament_id: @season.tournament_id)
    _roosters = Array.new
    
    _barns.each do |barn|
      barn.roosters.each  do |rooster|
        if rooster.season_id == @season.id 
          @barns.push(barn)
          break
        end
      end
    end
    @notSelected = Array.new
    @season.roosters.each do |rooster|
      if rooster.fight_id == nil
        @notSelected.push(rooster)
      end
    end
    
  
  end

  def new
    @season = Season.new
    @season.tournament_id = params[:format]
    @tournaments = Tournament.all
  end

  def edit
  end

  def create
    
    @season = Season.new(season_params)
  

    respond_to do |format|
      if @season.save
        format.html { redirect_to tournament_path(@season.tournament), notice: "Fecha creada" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to season_path(@season), notice: "Categoría actualizada exitósamente" }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @season.destroy

    respond_to do |format|
      format.html { redirect_to tournament_path(@season.tournament_id) }
    end
  end

  private
    def get_season
      @season = Season.find(params[:id])
    end

    def season_params
      params.require(:season).permit(:name, :tournament_id)
    end

end

app/views/seasons/_fights.html.erb
<div class="row">
    <div class="col-md-12">
        <table class="table" style="margin-top: 1.2rem; font-size: 15px;">
            <thead class="table-active">
                    <tr>
                        <th>#Pelea</th>
                        <th>Galpon #1 </th>
                        <th>Placa</th>
                        <th>Peso</th>
                        <th>VS</th>
                        <th>Galpon #2</th>
                        <th>Placa</th>
                        <th>Peso</th>
                        <th>Ver</th>
                    </tr>
                </thead>
            <tbody>
                <% Fight.where(season_id: @season.id).order(:number).each do |fight| %>
                        <% if fight.roosters[0] != nil and fight.roosters[1] != nil %>
                            <tr>
                                <td><%= fight.number %></td>
                                <td>
                                    <strong><%= fight.roosters[0].barn.name %></strong>
                                    - <%= fight.roosters[0].race  %> 
                                </td>
                                <td> <%= fight.roosters[0].plate  %></td>
                                <td> <%= fight.roosters[0].weight  %></td>
                                <td><strong> VS </strong> </td>
                                <td>
                                    <strong><%= fight.roosters[1].barn.name %></strong>
                                    - <%= fight.roosters[1].race  %>
                                </td>
                                <td> <%= fight.roosters[1].plate  %></td>
                                <td> <%= fight.roosters[1].weight  %></td>
                                <td> <%= link_to "Ver Pelea", fight_path(fight), :class => "btn btn-secondary", target: :_blank%></td>
                            </tr>
                        <%end%>
                    <% end %>
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
            <%= link_to "#", :class => "btn btn-outline-danger",:data => { :toggle => "modal", :target => "#notSelectedModal"} do %>
                <span> <i class="fa fa-trash-alt"></i> Gallos No Seleccionados </span>
            <% end %>
            <%= link_to "Sortear Peleas", new_fight_path(@season), :class => "btn btn-primary float-right" %>
        </div>
    </div>
</div>
<div class="row">
        <div class="col-md-12">
            <div class="modal fade" id="notSelectedModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" style="color:#333;">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Eliminar Galpon</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <table class="table">
                                    <thead class="table-active">
                                        <tr>
                                            <th scope="col">Galpon</th>
                                            <th scope="col">Color</th>
                                            <th scope="col">Peso </th>
                                            <th scope="col">Placa </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @notSelected.each do |rooster| %>
                                            <tr>
                                                <td> <%= rooster.barn.name %></td>
                                                <td> <%= rooster.race %></td>
                                                <td> <%= rooster.weight %></td>
                                                <td> <%= rooster.plate %></td>
                                            </tr>
                                        <%end%>
                                    </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

app/views/seasons/_form.html.erb
<%= form_for @season do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Nombre:", :class => "col-sm-4 col-form-label" %>
    <div class="col-sm-12">
      <%= f.text_field :name, :class => "form-control" %>
      <%= f.hidden_field :tournament_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-4 col-form-label"> Temporada </label>
    <div class="col-sm-12">
      
      <input type="text" class="form-control" value="<%=@season.tournament.name %>" disabled/>
    </div>  
  </div>
  
  <div class="form-actions row">
    <div class="col-sm-12">
      <div class="float-right">
        <%= link_to "Cancelar", seasons_path, :class => "btn btn-light" %>
        <%= f.submit "Guardar", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/seasons/_gallos.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
            <%= link_to "Registrar Galpon", new_barn_path(@season.tournament), :class => "btn btn-primary float-right" %>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table" style="margin-top: 1.2rem; font-size: 15px;">
            <thead class="table-active">
                <tr>
                    <th>Galpon</th>
                    <th>Lugar</th>
                    <% for i in 1..@season.tournament.quantity do %>
                        <th class="throoster">Gallo #<%= i%>(peso)</th>
                    <% end %>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                <% @barns.each do |barn| %>
                <tr>
                    <td><%= barn.name %></td>
                    <td><%= barn.place %></td>
                    <% @count = 0 %>
                    <% barn.roosters.each do |rooster|%>
                        <% if rooster.season_id == @season.id %>
                            <% @count += 1 %>
                            <td class="tdrooster">
                                (<%= rooster.plate %>)-
                                <%= rooster.race %>(<%= rooster.weight %>)
                            </td>
                        <%end%>
                    <%end%>
                    <% for i in @count..@season.tournament.quantity - 1 do%>
                        <td>-</td>
                    <%end%>
                    
                    <td><%= link_to barn_path(barn), :class => "btn btn-secondary" do %>
                        <span> <i class="fa fa-edit"></i> Editar </span>
                        <%end%>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/seasons/_results.html.erb
<div class="row">
    <div class="col-md-12">
        <table class="table" style="margin-top: 1.2rem; font-size: 15px;">
            <thead class="table-active">
                <tr>
                    <th scope="col">#Pelea</th>
                        <th scope="col">Galpon - Gallo </th>
                        <th scope="col">VS</th>
                        <th scope="col">Galpon - Gallo </th>
                        <th scope="col">Ganador </th>
                        <th scope="col">Tiempo </th>
                        <th scope="col">Placa </th>
                        <th scope="col">Peso </th>
                        <th scope="col">Pollon </th>
                        <th scope="col">Resultados </th>
                </tr>
            </thead>
            <tbody>
                <% @season.fights.each do |fight| %>
                    <% if fight.roosters[0] != nil and fight.roosters[1] != nil %>
                            <tr>
                                <td><%= fight.number %></td>
                                <td> 
                                    <strong>
                                        <%= fight.roosters[0].barn.name  %> 
                                    </strong> - 
                                        <%= fight.roosters[0].race  %> (<%= fight.roosters[0].weight  %> )
                                </td>
                                <td>VS</td>
                                <td>
                                    <strong><%= fight.roosters[1].barn.name  %></strong> 
                                    - <%= fight.roosters[1].race  %> (<%= fight.roosters[0].weight  %> ) 
                                </td>
                                <% if fight.winner == 0 %>
                                    <td>Empate</td>
                                    <td>-</td>
                                    <td>-</td>
                                    <td>-</td>
                                <% elsif fight.winner != nil  %> 
                                    <% fight.roosters.each do |rooster| %> 
                                        <% if rooster.id == fight.winner %>
                                           <td><%= rooster.barn.name %> - 
                                            <%= rooster.race %></td>
                                            <td> <%= fight.time %> </td>
                                            <td> <%= rooster.plate %></td>
                                            <td> <%= rooster.weight %></td>
                                        <% end %>
                                    <% end %>
                                       
                                <% else %>
                                    <td>-</td>
                                    <td>-</td>
                                    <td>-</td>
                                    <td>-</td>
                                <%end%>
                                <td>
                                    <% if fight.pollon == nil %> 
                                        -
                                    <%end%>
                                    <% if fight.pollon %>
                                        SI
                                    <%end%>
                                    <% if fight.pollon == false %> 
                                        NO
                                    <%end%>
                                </td>
                                <td> <%= link_to edit_fight_path(fight), :class => "btn btn-outline-info" do %>
                                        <span>
                                            <i class="fa fa-pencil-alt"></i> Ingresar Resultados
                                        </span>
                                    <% end %> </td>
                            </tr>
                        <%end%>  
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/seasons/_roosterForm.erb
<%= link_to "#", :class => "btn btn-secondary",
              :data => { :toggle => "modal", :target => "#addRooster#{barn.id}"} do %>
    <span>
        <i class="fa fa-add"></i> Agregar Gallo
    </span>
<% end %>
<div class="modal fade" id="addRooster<%=barn.id%>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Agregar Gallos para <%= barn.name %> </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <%= form_for(@rooster) do |f| %>
                <div class="modal-body">
                        <%= f.hidden_field :barn_id, :value => barn.id %> 
                        <div class="form-group row">
                            <%= f.label :season_id, "Fecha", :class => "col-sm-4 col-form-label" %>
                            <%= f.hidden_field :season_id, :value =>  @season.id %>
                        </div>
                        <div class="form-group row">
                            <%= f.label :race, "Color", :class => "col-sm-4 col-form-label" %>
                            <div class="col-sm-12">
                                <%= f.text_field :race, :class => "form-control" %>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <%= f.label :weight, "Peso", :class => "col-form-label" %>
                                <%= f.text_field :weight, :class => "form-control" %>
                            </div>
                            <div class="col-md-6">
                                <%= f.label :plate, "Placa", :class => "col-form-label" %>
                                <%= f.text_field :plate, :class => "form-control" %>
                            </div>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">
                        Cancelar
                    </button>
                    <%= f.submit "Guardar", :class => "btn btn-primary" %>
                </div>
            <%end%>
        </div>
    </div>
</div>

app/views/seasons/index.html.erb
<div class="container marketing card">
    <div class="row">
        <div class="col-md-6">
            <h4>FECHAS </h4>
        </div>
        <div class="col-md-6">
            <%= link_to "Nueva Temporada", new_season_path, :class => "btn btn-white float-right" %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped" style="margin-top:1.2rem;text-align:center;">
                <thead>
                    <tr>
                        <th scope="col">Temporada</th>
                        <th scope="col">Ver Galpones</th>
                        <th scope="col">Ver Peleas </th>
                        <th scope="col">Ver Tabla</th>
                    </tr>
                </thead>
                <tbody>
                    <% @seasons.each do |season| %>
                        <tr>
                            <td><%= season.name %></td>
                            <td>
                                <%= link_to "Ver Galpones", season_path(season), :class => "btn btn-outline-info" %>
                            </td>
                            <td>Ver Peleas</td>
                            <td>Ver Tabla</td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/seasons/new.html.erb
<div class="container marketing">
    <div class="row">
        <div class="col-md-12">
            <h4>Registrar Nueva Fecha </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/seasons/show.html.erb
<div class="container marketing">
    <div class="marketing card">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <h3> <%= @season.tournament.name %> - <%= @season.name %></h3>
                </div>
                <div class="col-2 float-right">
                    <button class="btn btn-label float-right btn-menu-seasons" data-name="barns"> Galpones </button>
                </div>
                <div class="col-2 float-right">
                    <button class="btn btn-label float-right btn-menu-seasons" data-name="fights"> Peleas </button>
                </div>
                <div class="col-2 float-right">
                    <button class="btn btn-label float-right btn-menu-seasons" data-name="results"> Resultados </button>
                </div>
            </div>
        </div>
    </div>
        <br/>
    <div class="card">
        <div class="card-body">
            <div class="menu-seasons" id="barns">
                <%= render "gallos"%>
            </div>
            <div class="menu-seasons hidden" id="fights">
                <%= render "fights"%>
            </div>
            <div class="menu-seasons hidden" id="results">
                 <%= render "results"%>
            </div>
        </div>
    </div>
</div>