config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :seasons
  resources :barns
  resources :tournaments
  resources :fights
  resources :roosters
end

app/models/tournament.rb
class Tournament < ApplicationRecord
    has_many :seasons
    has_many :barns
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  
  before_action :get_tournament, only: [:show, :edit, :update, :destroy]

  def index
    @tournaments = Tournament.all
  end

  def show

    @seasons = Season.where(tournament_id: @tournament.id).order('created_at DESC')
    @rooster = Rooster.new
    @barns = @tournament.barns.sort_by { |m| m.name.downcase }
    @barnsScore = @tournament.barns.sort_by { |m| m.score }

    @barns.each do |barn|
      if barn.score == nil
        barn.score = 0
        barn.totalTime = 0 
      end
      barn.roosters.each do |rooster|
        if rooster.played?
          if barn.played == nil
            barn.played = 0
            barn.lost = 0
            barn.tie = 0
            barn.won = 0
            barn.score = 0
            barn.pollon = 0
            barn.totalTime= 00
          end
          barn.played += 1 

          case rooster.score
          when 0
            barn.lost += 1 
          when 1
            barn.tie += 1
            barn.score += 1 
          when 3
            barn.won += 1
            barn.score += 3
            barn.totalTime += timeToSec(rooster.fight.time)
          when 4 
            barn.pollon += 1 
            barn.score += 4 
            barn.totalTime += timeToSec(rooster.fight.time)
          end
        end
      end
    end
    @barnsScore = @barns
    @barnsScore = @barnsScore.sort_by { |m| [ -m.score, m.totalTime.to_i ] }

  end

  def timeToSec(time)
    return ( time.split(":")[0].to_i * 60 ) + time.split(":")[1].to_i 
  end

  def calculateTotalTime(totalTime, fightTime)
    
    _totalTimeToSec = ( totalTime.split(":")[0].to_i * 60 ) + totalTime.split(":")[1].to_i 
    _fightTimeToSec = ( fightTime.split(":")[0].to_i * 60 ) + fightTime.split(":")[1].to_i 

    return _totalTimeToSec + _fightTimeToSec
  end
  def new
    @tournament = Tournament.new
  end

  def edit
  end

  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to tournaments_path, notice: "Categoría creada exitósamente" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tournament.update(season_params)
        format.html { redirect_to tournament_path(@tournament), notice: "Categoría actualizada exitósamente" }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_path }
    end
  end

  private
    def get_tournament
      @tournament = Tournament.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(:name,:quantity)
    end

end

app/views/tournaments/_form.html.erb
<%= form_for @tournament do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Nombre:", :class => "col-sm-4 col-form-label" %>
    <div class="col-sm-12">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :quantity, "Numero de Frentes:", :class => "col-sm-4 col-form-label" %>
    <div class="col-sm-12">
      <%= f.text_field :quantity, :class => "form-control" %>
    </div>
  </div>
  <div class="form-actions row">
    <div class="col-sm-12">
      <div class="float-right">
        <%= link_to "Cancelar", tournaments_path, :class => "btn btn-secondary" %>
        <%= f.submit "Guardar", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/tournaments/_score.html.erb
<div class="row">
    <div class="col">
        <h3>Tabla de Posiciones </h3>
    </div>
    <div class="col">
        <%= link_to "Registrar Nueva Fecha", new_season_path(@tournament), :class => "btn btn-primary float-right" %>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped" style="margin-top: 1.2rem;">
            <thead>
                <tr>
                    <th> #
                    <th >Galpon </th>
                    <th ># De Gallos</th>
                    <th >Pollon</th>
                    <th >Ganadas</th>
                    <th >Empate</th>
                    <th >Perdidas</th>
                    <th >Puntos</th>
                    <th >Tiempo</th>
                </tr>
            </thead>
            <tbody>
                <% @barnsScore.each_with_index do |barn, index|%>
                    <tr>
                        <td><%= index + 1 %></td>
                        <td><%= barn.name %></td>
                        <td><%= barn.played %></td>
                        <td><%= barn.pollon %></td>
                        <td><%= barn.won %></td>
                        <td><%= barn.tie %></td>
                        <td><%= barn.lost %></td>
                        <td><%= barn.score %></td>
                        <td><%= (barn.totalTime/60).to_s %>:<% if (barn.totalTime%60)<10 %>0<%end%><%= (barn.totalTime%60).to_s%> </td>
                    </tr>
                <% end %>
                <tr>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/tournaments/_tab1.html.erb
<div class="row">
    <div class="col">
        <h4> Mantenimiento Galpones </h4>
    </div>
    <div class="col">
        <%= link_to "Registrar Galpon", new_barn_path(@tournament), :class => "btn btn-primary float-right" %>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered" style="margin-top: 1.2rem;">
            <thead>
                <tr>
                    <th>Galpon</th>
                    <th>Lugar</th>
                    <%# <th>Ver </th> %>
                    <%# <th>Agregar</th> %>
                    <th>Operaciones</th>
                </tr>
            </thead>
            <tbody>
                <% @barns.each do |barn| %>
                <tr>
                    <td><%= barn.name %></td>
                    <td><%= barn.place %></td>
                    <td>
                        <%= link_to "#", :class => "btn btn-secondary",
                                      :data => { :toggle => "modal", :target => "#seeRooster#{barn.id}"} do %>
                        <span>
                            <i class="fa fa-search"></i>
                        </span>
                        <% end %>
                        <div class="modal fade" id="seeRooster<%=barn.id%>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Gallos de <%= barn.name %> </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <% @tournament.seasons.each do |season|%>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <h6 style="font-weight: bold;"> <strong> <%=season.name%> </strong> </h6>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <table class="table table-striped" style="font-size : 14px;">
                                                        <thead>
                                                            <tr>
                                                                <th>Id</th>
                                                                <th>Placa</th>
                                                                <th>Color</th>
                                                                <th>Peso </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <% barn.roosters.each do |rooster| %>
                                                                <% if rooster.season_id == season.id%>
                                                                    <tr>
                                                                        <td><%= rooster.id %></td>
                                                                        <td><%= rooster.plate %></td>
                                                                        <td><%= rooster.race %></td>
                                                                        <td><%= rooster.weight %> </td>
                                                                    </tr>
                                                                <%end%>
                                                            <%end%>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            
                                        <%end%>
                                        
                                    </div>
                                    <div class="modal-footer">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    <%# </td>
                    <td> %>
                        <%= link_to "#", :class => "btn btn-secondary",
                                      :data => { :toggle => "modal", :target => "#addRooster#{barn.id}"} do %>
                        <span>
                            <i class="fa fa-plus"></i> 
                        </span>
                        <% end %>
                        <div class="modal fade" id="addRooster<%=barn.id%>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Agregar Gallos para <%= barn.name %> </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <%= form_for(@rooster) do |f| %>
                                        <div class="modal-body" style="text-align: left;"> 
                                                <%= f.hidden_field :barn_id, :value => barn.id %> 
                                                <div class="form-group row">
                                                    <%= f.label :season_id, "Fecha", :class => "col-sm-4 col-form-label" %>
                                                    <div class="col-sm-12">
                                                        <%= f.select :season_id, options_from_collection_for_select(@seasons, :id, :name, :season_id), {} , :class => "form-control" %>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <%= f.label :race, "Color", :class => "col-sm-4 col-form-label" %>
                                                    <div class="col-sm-12">
                                                        <%= f.text_field :race, :class => "form-control" %>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <div class="col-md-6">
                                                        <%= f.label :weight, "Peso", :class => "col-form-label" %>
                                                        <%= f.text_field :weight, :class => "form-control" %>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <%= f.label :plate, "Placa", :class => "col-form-label" %>
                                                        <%= f.text_field :plate, :class => "form-control" %>
                                                    </div>
                                                </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-light" data-dismiss="modal">
                                                Cancelar
                                            </button>
                                            <%= f.submit "Guardar", :class => "btn btn-primary" %>
                                        </div>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                    <%# </td>
                    <td> %>
                        <%= link_to barn_path(barn), :class => "btn btn-secondary" do %>
                        <span> <i class="fa fa-edit"></i>  </span>
                        <%end%>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/tournaments/_tab2.html.erb
<div class="row">
    <div class="col">
        <h3> Fechas </h3>
    </div>
    <div class="col">
        <%= link_to "Registrar Nueva Fecha", new_season_path(@tournament), :class => "btn btn-primary float-right" %>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered" style="margin-top: 1.2rem;">
            <thead>
                <tr>
                    <th >Descripcion </th>
                    <%# <th >Detalle</th> %>
                    <th >Operaciones</th>
                </tr>
            </thead>
            <tbody>
                <% @tournament.seasons.each do |season| %>
                    <tr>
                        <td><%= season.name %></td>
                        <td>
                            <%= link_to season_path(season), :class => "btn btn-secondary" do %>
                                <span> <i class="fa fa-search"></i>  </span>
                            <%end%>
                        <%# </td>
                        <td> %>
                            <%= link_to "#", :class => "btn btn-outline-danger",:data => { :toggle => "modal", :target => "#deleteModal#{season.id}"} do %>
                                <span> <i class="fa fa-trash-alt"></i>  </span>
                            <% end %>
                            <div class="modal fade" id="deleteModal<%=season.id%>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" style="color:#333;">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Eliminar Fecha</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Al eliminar la <%= season.name %> eliminara todos los gallos y peleas registradas en esta.
                                        ¿Está seguro que desea eliminar la <strong><%= season.name %>?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                                        <%= link_to "Eliminar", season_path(season) ,  method: :delete, class: "btn btn-danger" %>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/tournaments/index.html.erb
<div class="container marketing card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <h4>TORNEOS </h4>
            </div>
            <div class="col-md-6">
                <%= link_to "Nueva Temporada", new_tournament_path, :class => "btn btn-primary float-right" %>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered" style="margin-top:1.2rem;text-align:center;">
                    <thead>
                        <tr>
                            <th scope="col">Temporada</th>
                            <th scope="col"> # de Frentes</th>
                            <th scope="col"> Detalle </th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @tournaments.each do |tournament| %>
                            <tr>
                                <td><%= tournament.name %></td>
                                <td><%= tournament.quantity %></td>
                                <td>
                                    <%= link_to "Detalle", tournament_path(tournament), :class => "btn btn-primary btn-outlined" %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
</div>

app/views/tournaments/new.html.erb
<div class="container marketing">
    <div class="row">
        <div class="col-md-12">
            <h4>Registrar Nueva Temporada </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/tournaments/show.html.erb
<div class="container">
    <div class="marketing card">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <h3> <%= @tournament.name %> </h3>
                </div>
                <div class="col-2 float-right">
                    <button class="btn btn-label float-right btn-menu-tournaments" data-name="barns"> Galpones </button>
                </div>
                <div class="col-2 float-right">
                    <button class="btn btn-label float-right btn-menu-tournaments" data-name="seasons"> Fechas </button>
                </div>
                <div class="col-2 float-right">
                    <button class="btn btn-label float-right btn-menu-tournaments" data-name="scores"> Posiciones </button>
                </div>
            </div>
        </div>
    </div>
        <br/>
    <div class="card">
        <div class="card-body">
            <div class="menu-tournaments" id="barns">
                <%= render "tab1"%>
            </div>
            <div class="menu-tournaments hidden" id="seasons">
                <%= render "tab2"%>
            </div>
            <div class="menu-tournaments hidden" id="scores">
                <%= render "score" %>
            </div>
            
            <!-- <div class="row">
                <ul class="nav nav-tabs tabs">
                    <li class="nav-item active">
                        <a class="nav-link" href="#tab1">Galpones</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="#tab2">Fechas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#tab3">Tablas </a>
                    </li>
                </ul>
                <div class="tab_container">
                    <div class="tab_content" id="tab1">
                        <%= render "tab1"%>
                    </div>
                    <div class="tab_content" id="tab2">
                        <%= render "tab2"%>
                    </div>
                    <div class="tab_content" id="tab3" style="color:black">
                        <%= render "score"%>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
    
    
    
</div>