config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :seasons
  resources :barns
  resources :tournaments
  resources :fights
  resources :roosters
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#" style="padding: 0">
        COLISEO TRADICIONAL DE GALLOS
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <% if @tournamentsBar != nil %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to @tournamentsBar.name, tournament_path(@tournamentsBar), class:"nav-link" %>
            </li>
          </ul>
        <%end%>
        
        <div class="navbar-left">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to "TORNEOS", tournaments_path, class:"nav-link" %>
            </li>
          
            <li class="nav-item active">
              <%= link_to "TABLAS", seasons_path, class:"nav-link" %>
            </li>
            <!-- <% if user_signed_in? %>
              <li class="nav-item">
                <div class="dropdown">
                  <button class="btn btn-green dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= user.email %>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete, :class => "dropdown-item" %>
                  </div>
                </div>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to "Iniciar sesión", new_user_session_path, :class => "nav-link" %></li>
              <li class="nav-item"><%= link_to "Registrarse", new_user_registration_path, :class => "nav-link" %></li>
            <% end %> -->
          </ul>
        </div>
      </div>
    </div>  
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coliseum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous" />
 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <% if notice %>
            <div class="alert alert-success alert-dismissable" style="margin-top: 20px; width: 100%">
              <%= notice %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    
    <%= yield %>
  </body>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'bootstrap.min' %>
</html>